cc_library(
    name = "ad_tree",
    srcs = [
        "ad_node.cpp",
        "ad_tree.cpp",
        "vary_node.cpp"
    ],
    hdrs = [
        "ad_node.h",
        "ad_tree.h",
        "contingency_table_node.h",
        "vary_node.h"

    ],
    deps = [
        "//urlearning/base:base",
    ],
    copts = ["-Wno-sign-compare"],
    visibility = ["//visibility:public"]
)
