cc_library(
    name="fileio",
    srcs = [
        "hugin_structure_writer.cpp"
    ],
    hdrs = [
        "hugin_structure_writer.h"
    ],
    copts = [],
    visibility = ["//visibility:public"],
    deps = [
        "//urlearning/base:base"
    ]
)
