cc_library(
    name="priority_queue",
    srcs = [
        "priority_queue.cpp"
    ],
    hdrs = [
        "priority_queue.h",
        "priority_queue-inl.h"
    ],
    copts = ["-Wno-sign-compare"],
    visibility = ["//visibility:public"],
    deps = [
        "//urlearning/base:base",
    ]
)
